apiVersion: apps/v1
kind: Deployment
metadata:
  name: counter
  namespace: efk-logging
  labels:
    app: counter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: counter
  template:
    metadata:
      labels:
        app: counter
    spec:
      containers:
        - name: counter
          image: busybox
          command: ['sh', '-c', 'i=0; while true; do echo "$i: $(date)" ; i=$((i+1)); sleep 1; done']
          resources:
            requests:
              cpu: 20m
              memory: 32Mi
            limits:
              cpu: 100m
              memory: 64Mi
